# Generated by Django 5.2.6 on 2025-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('multiplier', models.IntegerField()),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='generated_zips/%Y/%m/%d/')),
                ('classification_summary', models.JSONField(blank=True, null=True)),
                ('gan_used', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
